"""Markdown report generator."""

from __future__ import annotations

import os
from datetime import date
from pathlib import Path
from typing import Optional

from src.billing import BillingReport
from src.resources import ResourceReport


def generate_markdown(
    billing: BillingReport,
    resources: Optional[ResourceReport] = None,
    ai_recommendations: Optional[str] = None,
) -> str:
    today = date.today().isoformat()
    lines = [
        f"# GCP Cost Analysis — {today}",
        "",
        f"> Period: **{billing.period_start}** → **{billing.period_end}**  ",
        f"> Billing account: `{billing.billing_account_id}`",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total spend | **${billing.total_cost:,.2f}** {billing.currency} |",
        f"| vs previous period | {billing.total_delta} |",
    ]

    if resources:
        lines += [
            f"| Idle disks | {len(resources.idle_disks)} (~${resources.total_waste_estimate:,.0f}/mo waste) |",
            f"| Old snapshots | {len(resources.idle_snapshots)} |",
            f"| Underutilized node pools | {len(resources.underutilized_node_pools)} |",
        ]

    lines += ["", "---", "", "## Top Services by Cost", ""]

    if billing.services:
        lines.append("| Service | Cost | vs Previous |")
        lines.append("|---------|------|-------------|")
        for svc in billing.services:
            lines.append(f"| {svc.service} | ${svc.cost:,.2f} | {svc.delta_str} |")
    else:
        lines.append("_No service-level data available. Check billing account permissions._")

    if resources and resources.idle_disks:
        lines += [
            "",
            "---",
            "",
            f"## Idle Resources — Unattached Disks ({len(resources.idle_disks)})",
            "",
            "| Disk | Zone | Size | Type | Est. Monthly Cost |",
            "|------|------|------|------|-------------------|",
        ]
        for d in resources.idle_disks:
            lines.append(
                f"| `{d.name}` | {d.zone} | {d.size_gb}GB | {d.disk_type} | ${d.estimated_monthly_cost:.2f} |"
            )
        total_disk_waste = sum(d.estimated_monthly_cost for d in resources.idle_disks)
        lines.append(f"| **Total** | | | | **${total_disk_waste:.2f}/mo** |")

    if resources and resources.idle_snapshots:
        lines += [
            "",
            "---",
            "",
            f"## Idle Resources — Old Snapshots ({len(resources.idle_snapshots)})",
            "",
            "| Snapshot | Size | Age | Est. Monthly Cost |",
            "|----------|------|-----|-------------------|",
        ]
        for s in resources.idle_snapshots:
            lines.append(
                f"| `{s.name}` | {s.size_gb}GB | {s.age_days}d | ${s.estimated_monthly_cost:.2f} |"
            )

    if resources and resources.underutilized_node_pools:
        lines += [
            "",
            "---",
            "",
            f"## Underutilized GKE Node Pools ({len(resources.underutilized_node_pools)})",
            "",
            "| Cluster | Node Pool | Nodes | Avg CPU | Avg Memory |",
            "|---------|-----------|-------|---------|------------|",
        ]
        for n in resources.underutilized_node_pools:
            lines.append(
                f"| `{n.cluster}` | `{n.node_pool}` | {n.node_count} | {n.avg_cpu_pct:.1f}% | {n.avg_mem_pct:.1f}% |"
            )

    if ai_recommendations:
        lines += [
            "",
            "---",
            "",
            "## AI Recommendations",
            "",
            "*Powered by Gemini*",
            "",
            ai_recommendations,
        ]

    lines += [
        "",
        "---",
        "",
        f"*Generated by [gcp-cost-analyzer](https://github.com/n0rm4l-me/gcp-cost-analyzer) on {today}*",
    ]

    return "\n".join(lines)


def save_report(content: str, output_dir: str = "reports") -> Path:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    filename = path / f"{date.today().isoformat()}.md"
    filename.write_text(content, encoding="utf-8")
    return filename
